"""add cluster-level revisit cards

Revision ID: 250e22df5fd7
Revises: bfa02725e325
Create Date: 2026-06-23 19:09:29.798811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250e22df5fd7'
down_revision: Union[str, Sequence[str], None] = 'bfa02725e325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: autogenerate also proposed dropping capture_embeddings_embedding_idx
    # (the HNSW index, created via raw SQL rather than a SQLAlchemy Index
    # object) here — same false positive as in the previous two migrations.
    # That op.drop_index() call has been removed; do not restore it.
    op.add_column('revisit_cards', sa.Column('cluster_id', sa.String(), nullable=True))

    # op.add_column() (unlike op.create_table()) does not auto-create the
    # backing Postgres ENUM type, so it must be created explicitly first.
    card_type_enum = sa.Enum('individual', 'cluster', name='card_type')
    card_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('revisit_cards', sa.Column('card_type', card_type_enum, server_default='individual', nullable=False))
    op.alter_column('revisit_cards', 'capture_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'revisit_cards', 'clusters', ['cluster_id'], ['id'])

    # autogenerate doesn't detect CheckConstraints, so this is added by hand.
    op.create_check_constraint(
        'ck_revisit_cards_exactly_one_owner',
        'revisit_cards',
        "(capture_id IS NOT NULL AND cluster_id IS NULL) OR "
        "(capture_id IS NULL AND cluster_id IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_revisit_cards_exactly_one_owner', 'revisit_cards', type_='check')
    op.drop_constraint(None, 'revisit_cards', type_='foreignkey')
    op.alter_column('revisit_cards', 'capture_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('revisit_cards', 'card_type')
    sa.Enum(name='card_type').drop(op.get_bind(), checkfirst=True)
    op.drop_column('revisit_cards', 'cluster_id')
    # ### end Alembic commands ###
