"""create revisit_card_feedback table

Revision ID: 399d21e59392
Revises: 5607f612754a
Create Date: 2026-06-23 22:26:52.031585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '399d21e59392'
down_revision: Union[str, Sequence[str], None] = '5607f612754a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisit_card_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('revisit_card_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('opened', 'useful', 'not_useful', 'dismissed', 'next_action_taken', name='feedback_action'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_revisit_card_feedback_rating_range'),
    sa.ForeignKeyConstraint(['revisit_card_id'], ['revisit_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping capture_embeddings_embedding_idx
    # (the HNSW index, created via raw SQL rather than a SQLAlchemy Index
    # object) here — same false positive as in prior migrations. That
    # op.drop_index() call has been removed; do not restore it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisit_card_feedback')
    # ### end Alembic commands ###
