"""add extracted_text and extraction_error to captures

Revision ID: beed6164934a
Revises: fc25c1c860ac
Create Date: 2026-06-23 15:25:24.609578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beed6164934a'
down_revision: Union[str, Sequence[str], None] = 'fc25c1c860ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captures', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('extraction_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captures', 'extraction_error')
    op.drop_column('captures', 'extracted_text')
    # ### end Alembic commands ###
