"""create clusters and cluster_items tables

Revision ID: bfa02725e325
Revises: 79955ad85405
Create Date: 2026-06-23 19:02:33.674109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa02725e325'
down_revision: Union[str, Sequence[str], None] = '79955ad85405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('capture_id', sa.String(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id')
    )
    # NOTE: autogenerate also proposed dropping capture_embeddings_embedding_idx
    # (the HNSW index from the previous migration) here. That's a false
    # positive — the index was created via raw SQL, not a SQLAlchemy Index
    # object, so autogenerate doesn't recognize it as already existing. That
    # op.drop_index() call has been removed; do not restore it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_items')
    op.drop_table('clusters')
    # ### end Alembic commands ###
