"""create captures table

Revision ID: c613d419ffdc
Revises: 
Create Date: 2026-06-23 15:01:17.525441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c613d419ffdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('article', 'passage', 'video', 'image', 'note', name='source_type'), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('selected_text', sa.String(), nullable=True),
    sa.Column('user_note', sa.String(), nullable=True),
    sa.Column('label', sa.Enum('casual', 'return', name='label'), nullable=False),
    sa.Column('status', sa.Enum('saved', 'extracted', 'failed', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captures')
    # ### end Alembic commands ###
