"""create revisit_card_resources join table

Revision ID: f7369ee72e1a
Revises: 6bdc665ea059
Create Date: 2026-06-24 11:51:44.132051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7369ee72e1a'
down_revision: Union[str, Sequence[str], None] = '6bdc665ea059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisit_card_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('revisit_card_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['revisit_card_id'], ['revisit_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revisit_card_id', 'resource_id', name='uq_revisit_card_resources_card_resource')
    )
    # NOTE: autogenerate also proposed dropping capture_embeddings_embedding_idx
    # (the HNSW index, created via raw SQL rather than a SQLAlchemy Index
    # object) here — same false positive as in every prior migration that
    # touched another table. That op.drop_index() call has been removed;
    # do not restore it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisit_card_resources')
    # ### end Alembic commands ###
