"""create revisit_cards table

Revision ID: fc25c1c860ac
Revises: c613d419ffdc
Create Date: 2026-06-23 15:17:22.304354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc25c1c860ac'
down_revision: Union[str, Sequence[str], None] = 'c613d419ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revisit_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capture_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('why_saved', sa.String(), nullable=False),
    sa.Column('original_context', sa.String(), nullable=True),
    sa.Column('next_action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revisit_cards')
    # ### end Alembic commands ###
