"""create jobs table

Revision ID: ff1edaa0d80e
Revises: 399d21e59392
Create Date: 2026-06-23 22:46:29.011225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1edaa0d80e'
down_revision: Union[str, Sequence[str], None] = '399d21e59392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_type', sa.Enum('daily_batch', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='job_status'), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed dropping capture_embeddings_embedding_idx
    # (the HNSW index, created via raw SQL rather than a SQLAlchemy Index
    # object) here — same false positive as in prior migrations. That
    # op.drop_index() call has been removed; do not restore it.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
